# Setup
title: Clément Haëck
base-url: https://clementhaeck.com
permalink: pretty
avatar: "assets/img/avatar.jpg"
cover_bg_color: "rgb(78, 152, 162)"

# Gems
plugins:
  - jekyll-multiple-languages-plugin

# Optimize Jekyll
exclude:
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CNAME
  - build.sh

sass:
  sass_dir: _sass
  style: :compressed

author:
  name: Clément Haëck
  url: https://github.com/Descanonge/
  email: clement.haeck@locean.ipsl.fr

sidebar-pages: ["cv", "works"]

languages: ["en", "fr"]
languages_default: en
# exclude-from-localizations: ["img", "css"]
default_locale_in_subfolder: false
